name: flutter_web_server
version: "0.1.0"
description: flutter 프로젝트의 build/web을 자동으로 배포처리
homepage: https://flutter.ifwind.net
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies: 
  process_run: ^0.12.2+2
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
dev_dependencies:
  test: '>=1.15.0 <2.0.0'